# need to prepend AMBIENT base dir (e.g. /mnt/win_share/AMBIENT/)
alphapose_csvs = "CMM/Belmont/alphapose/raw"
gastnet_dir = "CMM/Belmont/gastnet/"
gastnet_vis_dir = "CMM/Belmont/gastnet_videos"
vid_dims = [1920, 1080]
orig_video_dir = "Andrea_S/Belmont/vids/aug11_vids/"