# need to prepend AMBIENT base dir (e.g. /mnt/win_share/AMBIENT/)
alphapose_csvs = "AMBIENT Lakeside/Analyses/unzipped_final/FINAL/alphapose/interpolated/"
gastnet_dir = "AMBIENT Lakeside/Analyses/gastnet/"
gastnet_vis_dir = "AMBIENT Lakeside/Analyses/gastnet_videos"
vid_dims = [1920, 1080]
orig_video_dir = "AMBIENT Lakeside/Analyses/extractions_lakeside/"