# need to prepend AMBIENT base dir (e.g. /mnt/win_share/AMBIENT/)
alphapose_csvs ="AMBIENT TRI/TRI_skeleton_trajectories/data/skel_data_alphapose/fixed_flips_and_cropped/interpolated/"
gastnet_dir = 'AMBIENT TRI/TRI_skeleton_trajectories/data/gastnet/'
gastnet_vis_dir = "AMBIENT TRI/Results/gastnet_videos/"
vid_dims = [1920, 1080]
orig_video_dir = "Andrea_S/TRI_data/"
